-- QUERY 1 :CATEGORY ANALYSIS

USE ecommerce_project;

-- checking which categories generate most values

SELECT P.CATEGORY,
COUNT(*) AS TOTAL_PRODUCTS,
AVG(PR.DISCOUNTED_PRICE) AS AVG_PRICE
FROM PRODUCTS P
JOIN PRICING PR
ON P.PRODUCT_ID = PR.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY AVG_PRICE DESC;

-- JOINS BOTH TABLES
-- SHOWS : AVG PRICE AND NUMBER OF PRODUCTS

-- I used SQL joins to analyze category-level pricing and product distribution.

-- Certain categories dominate the product inventory, indicating focus areas for business expansion and competition


-- QUERY 2 : TOP BRANDS ACCORDING TO REVENUE
-- TELLS US ABOUT WHICH BRAND WILL HAVE THE HIGHEST PRICING POWER
SELECT P.BRAND,
COUNT(*) AS TOTAL_PRODUCTS,
AVG(PR.DISCOUNTED_PRICE) AS AVG_PRICE
FROM PRODUCTS P
JOIN PRICING PR
ON P.PRODUCT_ID = PR.PRODUCT_ID
GROUP BY P.BRAND
ORDER BY AVG_PRICE DESC
LIMIT 10;

-- HIGH AVG PRICE - PREMIUM BRAND
-- LOW AVG PRICE - BUDGET BRAND

-- INSIGHTS:
-- BRAND ANGELFISH SELLS FEWER BUT HAS HIGH-VALUE PRODUCTS
-- BRAND FABHOMEDECOR SELLS FEWER BUT HAS HIGH-VALUE PRODUCTS

-- BRAND LADELA SELLS A BUT MORE BUT HAS A BIT LOW PRICE PRODUCTS


/*
Zed
W.A.Y
House This
Great Art
YK
Shagun
Myint
*/
-- ALL THESE BRANDS SELLS FEW BUT ALSO HAVE QUIET GOOD VALUE 

-- A small number of brands contribute to high-value products, suggesting strong brand-driven pricing power



-- QUERY 3
-- TELLS US ABOUT WHICH CATEGORIES RELY HEAVILY ON DISCOUNT


 SELECT P.CATEGORY,
 AVG(PR.DISCOUNT_PERCENT) AS AVG_DISCOUNT,
 COUNT(*) AS TOTAL_PRODUCTS
 FROM PRODUCTS P
JOIN PRICING PR
ON P.PRODUCT_ID = PR.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY AVG_DISCOUNT DESC;

-- HIGH DISCOUNTS = COMPETITIVE MARKET
-- LOW DISCOUNT - PREMIUM/MONOPOLY

-- INSIGHTS
-- CLOTHING BRANDS FOCUS MORE ON DISCOUNTS COMPARED TO OTHER BRNADS
-- OTHER BRANDS MAINTAIN A STABLE PRICE AND DISCOUNT MOSTLY BELOW 50%

-- Categories with higher average discounts indicate competitive markets where pricing strategies play a key role in sales.

-- QUERY 4 - PRICE V/S RATING


-- CHECKING THAT ONLY EXPENSIVE PRODUCTS HAVE BETTER RATINGS


SELECT 
      CASE
         WHEN PR.DISCOUNTED_PRICE < 1000 THEN "LOW"
         WHEN PR.DISCOUNTED_PRICE < 5000 THEN "MEDIUM"
         ELSE "HIGH"
     END AS PRICE_RANGE,
     AVG(P.PRODUCT_RATING) AS AVG_RATING,
     COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS P
JOIN PRICING PR
ON P.PRODUCT_ID = PR.PRODUCT_ID
GROUP BY PRICE_RANGE;

-- INSIGHTS
-- HIGH RANGE PRODUCTS NOT ALWAYS HAS HIGHEST RATINGS HIGH PRICE HAS AVG RATING OF 3.847368416033293

-- MID RANGE PRODUCTS HAVE THE HIGHEST RATINGS 3.914814820996037

-- Higher-priced products do not always guarantee better ratings, highlighting gaps in perceived value and customer satisfaction


-- export
SELECT * FROM products;
SELECT * FROM PRICING;



